repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.91.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.298
    hooks:
      - id: checkov
        args:
          - "--framework=terraform"
          - "--download-external-modules=true"
          - "--quiet"
          - "--skip-path=.terraform"
