name: ci
on:
  push:
  pull_request:

jobs:
  validate-and-sec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform fmt (check)
        run: terraform fmt -check

      - name: Terraform validate
        run: |
          terraform init -backend=false
          terraform validate

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install "checkov==3.2.298"

      - name: Checkov (Terraform)
        run: checkov -d . --framework terraform --download-external-modules true --quiet --skip-path .terraform
