name: CI - Terraform + Checks

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  validate-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      TF_IN_AUTOMATION: "true"
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools (pre-commit, Checkov, Prowler)
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit==3.7.1 checkov==3.2.306 prowler-cloud==3.11.3

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Prepare reports folder
        run: mkdir -p reports

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan (save output)
        run: terraform plan -no-color -input=false | tee reports/terraform-plan.txt

      - name: Run pre-commit (fmt/validate/Checkov -> reports/)
        run: pre-commit run --all-files || true

      - name: Prowler scan (HTML + JSON -> reports/)
        run: prowler gcp --project-ids "$GCP_PROJECT_ID" -M html json -o reports/
        continue-on-error: true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/**
