# =============================================================================
# .github/workflows/ci.yml — Pipeline GitHub Actions
# Repository: memoire-gcp-terraform
# Purpose   : fmt/validate/plan(+upload)/apply(main) + Prowler + artefacts
# Author    : RD
# Date      : 2025-10-01
#
# Notes importantes
# - Prowler ne s’exécute que si le plan Terraform a des changements.
# - Les rapports (Checkov/TF plan/Prowler) sont déposés dans `reports/`
#   puis uploadés en artefacts si présents.
# - La clé du SA CI est fournie via secret `GCP_SA_KEY`.
# =============================================================================

name: CI - Terraform + Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  TF_IN_AUTOMATION: "true"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Create reports folder
        run: mkdir -p reports

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: |
          set -e
          terraform plan -out=tfplan.bin
          terraform show -json tfplan.bin > reports/plan.json
          terraform show tfplan.bin > reports/plan.txt

      # Upload du plan sur PR uniquement (pour revue)
      - name: Upload TF plan (PRs)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: reports/plan.*

      # Apply auto uniquement sur main (démo)
      - name: Terraform apply (main only)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: terraform apply -auto-approve tfplan.bin

      # Python (pour Prowler installé via pip)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Prowler
        run: pip install prowler

      # Prowler seulement s’il y a des changements Terraform
      - name: Run Prowler
        if: ${{ steps.plan.outcome == 'success' && always() && contains((toJson(steps.plan.outputs) || ''), '') }}
        run: |
          prowler gcp --project-ids ${{ env.GCLOUD_PROJECT }} -M html json -o reports/ || true

      - name: Upload security reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/
          if-no-files-found: warn   # Affiche un warning si aucun rapport (comportement attendu si pas de changements)
