# =============================================================================
# .github/workflows/ci.yml — Pipeline GitHub Actions
# Repository: memoire-gcp-terraform
# Purpose   : fmt/validate/plan(+upload)/apply(main) + Prowler + artefacts
# Author    : RD
# Date      : 2025-10-01
#
# Notes importantes
# - Prowler ne s’exécute que si le plan Terraform a des changements.
# - Les rapports (Checkov/TF plan/Prowler) sont déposés dans `reports/`
#   puis uploadés en artefacts si présents.
# - La clé du SA CI est fournie via secret `GCP_SA_KEY`.
# =============================================================================

name: CI - Terraform + Checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

env:
  GCP_PROJECT_ID: direct-byte-472309-n3
  TF_IN_AUTOMATION: "true"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Create reports folder
        run: mkdir -p reports

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -out=tfplan

      - name: Upload TF plan (PRs)
        if: ${{ github.event_name == 'pull_request' && steps.plan.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Terraform apply (main only)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: terraform apply -auto-approve -input=false

      # --- Prowler ------------------------------------------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Prowler
        run: |
          python -m pip install --upgrade pip
          pip install prowler==3.11.3

      # Aide au diagnostic : on vérifie le compte et le projet actifs
      - name: Who am I? (GCloud)
        run: |
          echo "=== gcloud auth list ==="
          gcloud auth list
          echo "=== gcloud project ==="
          gcloud config get-value core/project
          echo "=== sample inventory ==="
          gcloud compute networks list --project "${{ env.GCP_PROJECT_ID }}" || true

      # Patch clé : on force Prowler à utiliser le même SA via l’ADC
      - name: Run Prowler
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        run: |
          prowler gcp --project-ids "${{ env.GCP_PROJECT_ID }}" -M html json -o reports/
          ls -la reports

      - name: Upload security reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/*
