name: CI - Terraform + Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: direct-byte-472309-n3
      GOOGLE_CLOUD_PROJECT: direct-byte-472309-n3
      TF_VAR_project_id: direct-byte-472309-n3
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 460.0.0"

      - name: Create reports folder
        run: mkdir -p reports

      - name: Terraform init
        run: terraform init -no-color -input=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: terraform plan -no-color -input=false -out=tfplan

      - name: Upload TF plan (PRs)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Terraform apply (main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      # --- Prowler après apply sur main ---
      - name: Setup Python
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Prowler
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: pip install "prowler-cloud==3.11.3"

      - name: Run Prowler
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          prowler gcp --project-ids $PROJECT_ID -M html json -o reports/

      - name: Upload security reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/**
          if-no-files-found: warn
